package com.bi.mobile.download.format.dataenum;

public enum DownLoadFormatEnum {
	DATE_ID, HOUR_ID, PLAT_ID, VERSION_ID, QUDAO_ID, CHANNEL_ID, CITY_ID, MACCLEAN, MEDIA_ID, SERIAL_ID, PROVINCE_ID, ISP_ID,TIMESTAMP, IP, DEV, MAC, VER, NT, MID, IH, SID, RT,IPHONEIP,CL,FUDID,MESSAGEID;
}
