package com.bi.client.fact.month;

public enum HsLogFormatEnum {
	
	DATE_ID,VERSION_ID,PROVINCE_ID,MAC,ISP_ID,USERNAME,USERTYPE,DOMAIN,VERSION,SOURCEIP,REASON,NETWORKTYPE,HOMESERVER,LOGINTIME,LOGOUTTIME,CHANNELID,UID,UIDTYPE,UPLOADFLUX,DOWNLOADFLUX;
}
