package com.bi.mobile.playtm.format.dataenum;

public enum PlayTMOutIHFormatEnum {

	//DATE_ID,HOUR_ID,PLAT_ID,VERSION_ID,QUDAO_ID,CHANNEL_ID,CITY_ID,MAC_CODE,MEDIA_ID,SERIAL_ID,PROVINCE_ID,ISP_ID,TIMESTAMP, IP, DEV, MAC, VER, NT, IH, SPOS, EPOS, VTM, SID, PN,TU,PTYPE,PBRE,RT,IPHONEIP,CL;

	DATE_ID,HOUR_ID,PLAT_ID,VERSION_ID,QUDAO_ID,CITY_ID,MACCLEAN,PROVINCE_ID,ISP_ID,TIMESTAMP, IP, DEV, MAC, VER, NT, IH, SPOS, EPOS, VTM, SID, PN,TU,PTYPE,PBRE,RT,IPHONEIP,CL;

}
