package com.bi.common.logenum;

public enum StuckEnum {
    TIMESTAMP, IP, DEV, MAC, VER, NT, INFOHASH, SERVERIP, BUFFEROK, STUCKPOSITION, STUCKTIME, DOWNLOADRATE, STREAMID, STUCKREASION, PLAYERTYPE, REPORTTIME, USERIP, CLARITY;

}
