package com.bi.common.logenum;

public enum FormatBootEnum {
    DATE_ID, HOUR_ID, PROVINCE_ID, CITY_ID, ISP_ID, PLAT_ID, QUDAO_ID, VERSION_ID, CLIENT_IP, MAC, START_TYPE, OS, ERROR_CODE, HC, HARDWARE_ACCELERATION, YY, TRAY_LIMIT, TIMESTAMP

}
