package com.bi.common.logenum;

public enum FormatDownloadEnum {
    DATE_ID, HOUR_ID, PROVINCE_ID, CITY_ID, ISP_ID, PLAT_ID, QUDAO_ID, VERSION_ID, INFOHASH_ID, SERIAL_ID, MEDIA_ID, CHANNEL_ID, MEDIA_NAME, MAC_CODE, FUDID, TIMESTAMP, NET_TYPE, CL, MESSAGE_ID

}
