package com.bi.common.logenum;

public enum MPVFormatEnum {
	DATE_ID,HOUR_ID, PROVINCE_ID,CITY_ID, ISP_ID, PLAT_ID, QUDAO_ID, VERSION_ID, IP, MAC_CODE, FCK, SESSION_ID, 
	USER_ID,USER_FLAG, URL, URL_FIRST_ID, URL_SECOND_ID, URL_THIRD_ID, INTER_SEARCH_KEYWORD, INTER_PAGE, 
	REFER_URL, REFRE_FIRST_ID, REFER_SECOND_ID, REFER_THIRD_ID, OUTER_SEARCH_KEYWORD, OUTER_PAGE,
	BROWSE, SYSTEM, VISIT_TIME,TIME_STAMP, PROTOCOL, RPROTOCOL, 
	CLIENT_FLAG, FPC, PV_ID, CONFIG, EXT, USERAGENT, PVSTEP, PVSESTEP, SEIDCOUNT, TA;
}
