package com.bi.common.logenum;

public enum PlayFormatEnum {
	
	DATE_ID,HOUR_ID, PROVINCE_ID,CITY_ID, ISP_ID, PLAT_ID, QUDAO_ID, 
	VERSION_ID, IP, MAC_CODE, FCK, SESSION_ID,  USER_ID,USER_FLAG, 
	INFOHASH_ID, SERIAL_ID, MEDIA_ID,CHANNEL_ID, MEDIA_NAME, MEDIA_TYPE_ID,
	URL, URL_FIRST_ID, URL_SECOND_ID, URL_THIRD_ID, 
	REFERURL, REFRE_FIRST_ID, REFER_SECOND_ID, REFER_THIRD_ID, OUTER_SEARCH_KEYWORD, OUTER_PAGE,
	TIME_STAMP, PROTOCOL, RPROTOCOL, CLIENT_FLAG,  FPC, PV_ID, 
	CONFIG, VV_ID, LIAN, PLATFORM,  VIDEO_LENGTH, FMT, EXT, 
	PVSTEP,PVSESTEP, SEIDCOUNT;
}
