package com.bi.mobile.comm.constant;

public enum ConstantEnum {

	MAC, MAC_LONG, TIMESTAMP,NT,RT, DATE_ID, HOUR_ID, PROVINCE_ID, CITY_ID, ISP_ID, CHANNEL_ID, MEIDA_ID, SERIAL_ID, SERVER_ID, SERVERROOM_ID, SERVERROOM_NAME, DM_COMMON_INFOHASH_FILEPATH, DM_MOBILE_PLATY_FILEPATH, DM_MOBILE_QUDAO_FILEPATH, DM_MOBILE_SERVER_FILEPATH, DM_MOBILE_VERSION_FILEPATH, IPTABLE_FILEPATH, COLUMNSUMKEY, ENUMCLASSTYPE, SUMCOL, INPUT_PATH, OUTPUT_PATH, CONFIG_FILE_PATH, LOCAL, DM_COMMON_INFOHASH, DM_MOBILE_PLATY, DM_MOBILE_QUDAO, DM_MOBILE_SERVER, DM_MOBILE_VERSION, IP_TABLE,NUMERATOR,DENOMINATOR,TOPNURL,TOPNURL_FILEPATH;

}
