package com.bi.mobile.fbuffer.format.dataenum;

public enum FbufferOutIHFormatEnum {

	DATE_ID,HOUR_ID,PLAT_ID,VERSION_ID,QUDAO_ID,CITY_ID,MACCLEAN,PROVINCE_ID,ISP_ID,SERVER_ID,TIMESTAMP, IP, DEV, MAC, VER, NT, IH, SERVERIP, OK, BPOS, BTM, DRATE,SID, NRATE,MSOK,PTYPE,RT,IPHONEIP,CL,MID,EID,VID,VT;
	//DATE_ID,HOUR_ID,PLAT_ID,VERSION_ID,QUDAO_ID,CHANNEL_ID,CITY_ID,MAC_CODE,MEDIA_ID,SERIAL_ID,PROVINCE_ID,ISP_ID,SERVER_ID,TIMESTAMP, IP, DEV, MAC, VER, NT, IH, SERVERIP, OK, BPOS, BTM, DRATE,SID, NRATE,MSOK,PTYPE,RT,IPHONEIP,CL,MID,EID,VID,VT;
	
}
